### ISSUE TITLE
Allow control over return type of parse_duration

### ISSUE THREAD

**Issue by Flix6x** [isodate/isodate#13]
Would you consider my PR https://github.com/gweis/isodate/pull/64? If so, I'd gladly make the PR here, too.

**Comment by hugovk** [comment]
Hi! I think that'd be fine as long as:

* The existing, default behaviour doesn't change (as is the case with that PR)
* Tests are added
* Perhaps rename `as_timedelta_if_possible`? Naming things are hard, maybe something like `prefer_timedelta=True` or `prefer_return="timedelta"`? Would be good to see if there's other naming used by other libraries, but I understand this is difficult to search for!
