### ISSUE TITLE
Next release roadmap

### ISSUE THREAD

**Issue by garf365** [isodate/isodate#15]
Hi Everyone,

Firstly, thank you for your work on this lib to maintain it up to date !

I need the control over return type of parse duration which have been done in MR #14. I would like to know if a new release with this modification have been planned in several days ? Indeed, if you have already planned this for this next days, I can wait for a new release. Otherwise, I will do in other way, but it would be less elegant than using this up to date library.

Thank you in advance

Garf

**Comment by hugovk** [comment]
Hi! I'll make a release later today.

**Comment by garf365** [comment]
Perfect ! Thank you so much !

**Comment by garf365** [comment]
Thank you ! I will use it right now
