### ISSUE TITLE
Move to an organization like jazzband

### ISSUE THREAD

**Issue by aucampia** [isodate/isodate#2]
I really would like to see this under an organization that will have some longevity, and once it is there we can maybe consider using https://www.python.org/dev/peps/pep-0541/ to get isodate back.

One option is to move this under @jazzband (see <https://jazzband.co/>).

I'm not sure what your feeling is about this, if you are good with it then maybe the right way to start is just move isodate2, and then after moving get isodate back using PEP 541. Any thoughts you have on this would be welcome.

**Comment by hugovk** [comment]
Hi! Good idea, I've moved it to an org called https://github.com/isodate and we can get it into shape. Would you like to join?

**Comment by aucampia** [comment]
I would gladly join yes, I have emailed @gweis also, and will try various ways of reaching him. He seems to be somewhat active in some places and all that is needed is that he gives you ownership of the package on pypi to publish to isodate which I'm sure he is willing to do if he realizes the problem.
